#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.88:3306/mybaby?useUnicode=true&characterEncoding=utf8
    username: mybaby
    password: mybaby20170606


###############################################


#   thymeleaf 相关设置
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
#spring.thymeleaf.mode的默认值是HTML5，其实是一个很严格的检查，
#改为LEGACYHTML5可以得到一个可能更友好亲切的格式要求。
#LEGACYHTML5需要搭配一个额外的库NekoHTML才可用
#		<dependency>
#			<groupId>net.sourceforge.nekohtml</groupId>
#			<artifactId>nekohtml</artifactId>
#			<version>1.9.15</version>
#		</dependency>
    mode: LEGACYHTML5

###############################################



#开MYBATIS日志打印 修改level及包名级别为debug 设置日志保存目录
logging:
  level:
    net.vv2.baby.mapper: DEBUG
  file: var/log/myapp.log


  ###############################################